### PR TITLE
Add @consideRatio as a maintainer

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Hmm, maybe that should have been `[ci-skip]`? 🤔

**Comment by consideRatio** [comment]
Thanks @dhirschfeld! :heart:

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
It doesn't look like AppVeyor is set up correctly:
```
Build started
git clone -q https://github.com/conda-forge/jupyterhub-ldapauthenticator-feedstock.git C:\projects\jupyterhub-ldapauthenticator-feedstock-3csax
git fetch -q origin +refs/pull/2/merge:
git checkout -qf FETCH_HEAD
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

I don't think there should even be an AppVeyor CI!

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
@conda-forge/core - help! The AppVeyor CI is broken & I'm not sure how to either fix or simply remove it!

**Comment by dhirschfeld** [comment]
Also seeing this in the logs:
```
Distribution /home/conda/feedstock_root/build_artifacts/noarch/jupyterhub-ldapauthenticator-1.2.2-py_1001.tar.bz2 is new for conda-forge, but no upload is taking place because the BINSTAR_TOKEN is missing.
```

Not sure if that is important. There is a `BINSTAR_TOKEN` in the `conda-forge.yml`

**Comment by xhochy** [comment]
This is a `noarch` package, so AppVeyor should not even run. You can ignore it for now.

**Comment by dhirschfeld** [comment]
I'll go ahead and merge and see if things work on master...

**Pull request merged**
